### ISSUE TITLE
Wizard choosing Table unsorted names

### ISSUE THREAD

**Issue by rzechu** [SQLPlayer/SCD-Merge-Wizard#2]
Hello,
On 2nd step of wizard after I choose connection string when I click Table, View or Synonym combobox the list of tables is unsorted it's hardly to find table when datbase has 100+ tables.
I know there's filter but It shouldn't be problem to just sort table names in this list.

**Comment by NowinskiK** [comment]
Thank you for your vote. In fact, it can be a nuisance to the user. I will check it and correct soon.

**Comment by jwk6** [comment]
@NowinskiK Will you take a pull request for this enhancement?  I've implemented support for IComparable on MyDBObject, and some manual testing works.

I haven't done a Pull Request here on Github yet though, so may need some help.  ;-)

**Comment by NowinskiK** [comment]
Yes, sure, go ahead. Create PR here and I will take a look.

**Comment by jwk6** [comment]
Done. Please check it out.
