### ISSUE TITLE
Upgrade to the latest version of .Net Framework 

### ISSUE THREAD

**Issue by jwk6** [SQLPlayer/SCD-Merge-Wizard#21]
Executing ScdMergeWizard.exe will result in the following if .Net Framework 3.5 is not installed. This is increasingly difficult to deal with, because most organizations do not have the group policy configuration that will allow the download to succeed. And, selecting "Skip this installation" will result in a silent failure to run the application.

Can we release a version of SCD Merge Wizard built with .Net Framework 4.8? 

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-framework 

![image](https://github.com/Azure-Player/SCD-Merge-Wizard/assets/20860172/2b85547b-c2be-4d67-a5f6-e4059fd6a058)

![image](https://github.com/Azure-Player/SCD-Merge-Wizard/assets/20860172/693ed823-d012-4451-9d54-8547a94117ee)

**Comment by NowinskiK** [comment]
I'm happy for you to do this. There is some additional efforts required due to old libraries in use. 
If you are able to rework this - raise a PR and I will review and release.
