### ISSUE TITLE
Record changes in multiple column

### ISSUE THREAD

**Issue by akashvjoshi** [SQLPlayer/SCD-Merge-Wizard#3]
I have a requirement where each ID has multiple values and I need to record (SCD type 2) if anything changes in any of those values.

Let me explain it using an example:
We have a table with person's name, address, telephone number, spouse name. I want to add an extra record if any of the details - address, telephone number or spouse name changes for that person. How do I achieve that?

**Comment by NowinskiK** [comment]
In a case when you want to track more columns changes – simply, in Step: Transformations, do set up ‘SCD2’ for ‘Address’ in ‘Transformation’ column rather than SCD1. That’s all.

**Comment by akashvjoshi** [comment]
Thank you for your response. I am doing what you suggested and getting a below error:

The MERGE statement attempted to UPDATE or DELETE the same row more than once. This happens when a target row matches more than one source row. A MERGE statement cannot UPDATE/DELETE the same row of the target table multiple times. Refine the ON clause to ensure a target row matches at most one source row, or use the GROUP BY clause to group the source rows.

**Comment by jwk6** [comment]
It's been a long time on this issue. Most likely this was a business key or data value issue.

Could we just move the question and the answer to a FAQ in the wiki?

**Comment by NowinskiK** [comment]
@akashvjoshi, I believe it's a way how you're getting the data from the source. GROUP BY not gonna help here as I don't want to encapsulate the logic of selecting the latest record of a set for particular business key.
What did you mean by "refine ON clause"? How? I need an example here if you keen to share.

**Comment by NowinskiK** [comment]
@jwk6 let's wait a week or two and if no reply - move it to Wiki/faq.

**Comment by akashvjoshi** [comment]
It's been a very long time since I submitted this. I somehow achieved what I wanted but I don't remember it now. Let's close this thread and move it to Archive.
