### ISSUE TITLE
Error in DBHelper class

### ISSUE THREAD

**Issue by zakwillis** [SQLPlayer/SCD-Merge-Wizard#4]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1752	Interop type 'DataLinksClass' cannot be embedded. Use the applicable interface instead.	ScdMergeWizard	C:\InfoRhino\SoftwareTesting\SCD-Merge-Wizard-master\SCD-Merge-Wizard-master\ScdMergeWizard\Database\DbHelper.cs	95	Active

**Comment by NowinskiK** [comment]
Please provide more information about your environment.

**Comment by zakwillis** [comment]
Hi there, just for completeness. Environment is windows 10.net framework 4.6.2. Local drive used.

**Comment by NowinskiK** [comment]
@jwk6, are you facing this issue on your PC?

**Comment by jwk6** [comment]
@NowinskiK No, this has never happened to me.

**Comment by NowinskiK** [comment]
@zakwillis, I'm closing this and similar issue as we can not reproduce the problem. Please try to open the code on a different machine.
