### ISSUE TITLE
DBHelper class interoperability error.

### ISSUE THREAD

**Issue by zakwillis** [SQLPlayer/SCD-Merge-Wizard#5]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1752	Interop type 'ConnectionClass' cannot be embedded. Use the applicable interface instead.	ScdMergeWizard	C:\InfoRhino\SoftwareTesting\SCD-Merge-Wizard-master\SCD-Merge-Wizard-master\ScdMergeWizard\Database\DbHelper.cs	96	Active

**Comment by NowinskiK** [comment]
Please provide more information about your environment.

**Comment by zakwillis** [comment]
Hi there. Windows 10, Visual Studio 2017. Admittedly compiled with 4.6.2 .net framework.

**Comment by NowinskiK** [comment]
@zakwillis, I'm closing this and similar issue as we can not reproduce the problem. Please try to open the code on a different machine.
