### ISSUE TITLE
Restricted zone

### ISSUE THREAD

**Issue by zakwillis** [SQLPlayer/SCD-Merge-Wizard#6]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file Formz\ConnectDbForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	ScdMergeWizard			

I deleted all resx files to let VS regenerate them.

**Comment by NowinskiK** [comment]
What's your environment (Windows, .NET Framework, Visual Studio)?
I'm guessing that you're running the app from source code in VS, right?
If so, do not use any network drive/path to avoid the issue.

**Comment by zakwillis** [comment]
Hi there. Running it in .Net 4.6.2 (realise yours is an earlier version). Running from a local drive on C:\InfoRhino etc.
Windows 10.

**Comment by NowinskiK** [comment]
@zakwillis, I'm closing this and similar issue as we can not reproduce the problem. Please try to open the code on a different machine.
