### ISSUE TITLE
ZIP archive install

### ISSUE THREAD

**Issue by jwk6** [SQLPlayer/SCD-Merge-Wizard#7]
Can you please create a zip install option?  This will prevent having to jump through a million hoops with Windows SmartScreen and installing the unsigned MSI file. 

Thanks

**Comment by jwk6** [comment]
@NowinskiK Thanks for considering this. I suppose the best solution is to sign the MSI, but in the mean time this seems to be a good option.

**Comment by NowinskiK** [comment]
ZIP will be added to each release beginning from [v.4.3](https://github.com/SQLPlayer/SCD-Merge-Wizard/releases/tag/v.4.3)
