### ISSUE TITLE
Missing space in the generated ON clause

### ISSUE THREAD

**Issue by jwk6** [SQLPlayer/SCD-Merge-Wizard#9]
For example, in the ON clause the comparisons of the business keys are missing a leading space character before the 'AND' keyword.  It's syntactically OK on SQL Server because the delimited identifiers enclosed in square brackets. However, it's visually annoying, and would result in a syntax error if the square bracket were removed.

```
	FROM [staging].[CustomerInvoiceJournal]
) as [source]
ON
(
	[source].[DATAAREAID] = [target].[DataAreaID]AND
	[source].[PARTITION] = [target].[Partition]AND
	[source].[SYSRECID] = [target].[SysRecID]
)
```

**Comment by jwk6** [comment]
I think I may already have a fix for this one ready to go.  ;-)

**Comment by NowinskiK** [comment]
Go ahead. I've just tested and merged your previous change.

**Comment by NowinskiK** [comment]
Which type is that? SCD2 / all?

**Comment by jwk6** [comment]
I was focusing on SCD1, but looking at this a little closer it looks like all types are affected. Will take a little more work to clean them all up.

**Comment by NowinskiK** [comment]
Yes, I found all of them and will push in a minute.

**Comment by jwk6** [comment]
@NowinskiK There's an "OR" on line 405 
`
query.Append(makeColumnComparer(leftColumns, rightColumns, "OR", true, 1));
`
Check out how it's handled in makeColumnComparer.  How about we do the same thing in makeColumnEqualator method?

**Comment by jwk6** [comment]
@NowinskiK Seems like that may leave an extra " " (space) in some cases, but that does *not* bother me.  How about you?

**Comment by NowinskiK** [comment]
No, let's do it right once started working on that. Good spot!
I changed it now and apply space to the function. Take a look now.

**Comment by jwk6** [comment]
Okay, I'll take a look.

Question - How do handle pulling down the code in the pull request to build and test, without actually completing the merge?

**Comment by NowinskiK** [comment]
Good question. I don't know. Still learning GitHub.
